import mongoose from 'mongoose';
import NotificationTemplate from '../models/NotificationTemplate';
import EmailConfig from '../models/EmailConfig';
import dotenv from 'dotenv';

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/piecejob';

const templates: any[] = [
  // --- ACCOUNT ---
  {
    templateCode: 'WELCOME_EMAIL',
    channel: 'EMAIL',
    category: 'ACCOUNT',
    description: 'General welcome email for new users.',
    trigger: 'User Registration',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Welcome to PieceJob, {{firstName}}!',
    body: '<h1>Welcome aboard!</h1><p>Hi {{firstName}}, thank you for joining PieceJob. We are excited to have you with us.</p><p>Start exploring services today!</p>',
    plainTextBody: 'Hi {{firstName}}, Welcome to PieceJob! We are excited to have you with us.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'WELCOME_PROVIDER',
    channel: 'EMAIL',
    category: 'ACCOUNT',
    description: 'Specific welcome email for service providers.',
    trigger: 'Provider Registration',
    recipient: 'Provider',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Welcome to the PieceJob Pro Network!',
    body: '<h1>Ready to Earn?</h1><p>Hi {{firstName}}, welcome to our network of professionals. Complete your profile and verification to start receiving jobs.</p>',
    plainTextBody: 'Hi {{firstName}}, Welcome to the PieceJob Pro Network! Complete your profile to start earning.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'EMAIL_VERIFICATION',
    channel: 'EMAIL',
    category: 'ACCOUNT',
    description: 'Email containing verification code for new email address.',
    trigger: 'Email Change Request',
    recipient: 'User',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Verify Your Email Address',
    body: '<p>Your verification code is: <b>{{code}}</b></p><p>This code will expire in 30 minutes.</p>',
    plainTextBody: 'Your verification code is: {{code}}. This code will expire in 30 minutes.',
    placeholders: ['code'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'PASSWORD_RESET',
    channel: 'EMAIL',
    category: 'ACCOUNT',
    description: 'Forgot password reset link.',
    trigger: 'Forgot Password Request',
    recipient: 'User',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Reset Your PieceJob Password',
    body: '<p>Hi {{firstName}},</p><p>You requested a password reset. Click the link below to set a new password:</p><p><a href="{{resetLink}}">Reset Password</a></p><p>If you did not request this, please ignore this email.</p>',
    plainTextBody: 'Hi {{firstName}}, reset your password using this link: {{resetLink}}',
    placeholders: ['firstName', 'resetLink'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'PASSWORD_RESET_SUCCESS',
    channel: 'EMAIL',
    category: 'ACCOUNT',
    description: 'Confirmation that password was reset via forgot password flow.',
    trigger: 'Password Reset Completed',
    recipient: 'User',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Password Reset Successful',
    body: '<p>Hi {{firstName}}, your password has been successfully reset. You can now login with your new password.</p>',
    plainTextBody: 'Hi {{firstName}}, your password has been successfully reset.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'ACCOUNT_LOCKED',
    channel: 'EMAIL',
    category: 'ACCOUNT',
    description: 'Alert when account is locked due to too many failed login attempts.',
    trigger: 'Security Lockout',
    recipient: 'User',
    priority: 'URGENT',
    language: 'EN',
    subject: 'Security Alert: Account Temporarily Locked',
    body: '<p>Hi {{firstName}}, your account has been locked due to multiple failed login attempts. Please contact support if this was not you.</p>',
    plainTextBody: 'Hi {{firstName}}, your account has been locked due to multiple failed login attempts.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'ACCOUNT_DELETION_REQUEST',
    channel: 'EMAIL',
    category: 'ACCOUNT',
    description: 'Request for account deletion.',
    trigger: 'Account Deletion Requested',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Account Deletion Request Received',
    body: '<p>Hi {{firstName}}, we have received your request to delete your account. Your account will be queued for removal in 30 days.</p>',
    plainTextBody: 'Hi {{firstName}}, we have received your request to delete your account.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'ACCOUNT_DELETED_CONFIRMATION',
    channel: 'EMAIL',
    category: 'ACCOUNT',
    description: 'Confirmation that account deletion is complete.',
    trigger: 'Account Deleted',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Your PieceJob Account has been Deleted',
    body: '<p>Goodbye {{firstName}}, your account and data have been removed from our system as requested.</p>',
    plainTextBody: 'Goodbye {{firstName}}, your account has been deleted.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- SECURITY ---
  {
    templateCode: 'LOGIN_ALERT',
    channel: 'EMAIL',
    category: 'SECURITY',
    description: 'Security alert for a new successful login.',
    trigger: 'User Login',
    recipient: 'User',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Security Alert: New Login Detected',
    body: '<p>Hi {{firstName}},</p><p>We detected a new login to your PieceJob account.</p><ul><li>Time: {{time}}</li><li>IP Address: {{ip}}</li></ul><p>If this was not you, please secure your account immediately.</p>',
    plainTextBody: 'Hi {{firstName}}, a new login was detected on your account at {{time}} from IP {{ip}}.',
    placeholders: ['firstName', 'time', 'ip'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'NEW_DEVICE_LOGIN',
    channel: 'EMAIL',
    category: 'SECURITY',
    description: 'Alert when a login occurs from an unrecognized device.',
    trigger: 'New Device Login',
    recipient: 'User',
    priority: 'HIGH',
    language: 'EN',
    subject: 'New Device Login Detected',
    body: '<p>Hi {{firstName}}, your account was accessed from a new device: <b>{{deviceName}}</b> at {{time}}.</p>',
    plainTextBody: 'Hi {{firstName}}, new device login detected: {{deviceName}} at {{time}}.',
    placeholders: ['firstName', 'deviceName', 'time'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'SUSPICIOUS_LOGIN_ALERT',
    channel: 'EMAIL',
    category: 'SECURITY',
    description: 'Alert for suspicious login behavior (e.g., unusual location).',
    trigger: 'Suspicious Activity Detected',
    recipient: 'User',
    priority: 'URGENT',
    language: 'EN',
    subject: 'Suspicious Login Attempt Blocked',
    body: '<p>Hi {{firstName}}, we blocked a suspicious login attempt from <b>{{location}}</b>.</p>',
    plainTextBody: 'Hi {{firstName}}, we blocked a suspicious login attempt from {{location}}.',
    placeholders: ['firstName', 'location'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'PASSWORD_CHANGED',
    channel: 'EMAIL',
    category: 'SECURITY',
    description: 'Confirmation of manual password change within settings.',
    trigger: 'Password Changed',
    recipient: 'User',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Security Notice: PieceJob Password Changed',
    body: '<p>Hi {{firstName}},</p><p>This is a confirmation that your PieceJob password was successfully changed on <b>{{time}}</b>.</p><p>If you did not authorize this change, please contact support immediately.</p>',
    plainTextBody: 'Hi {{firstName}}, your password was successfully changed on {{time}}.',
    placeholders: ['firstName', 'time'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'TWO_FACTOR_ENABLED',
    channel: 'EMAIL',
    category: 'SECURITY',
    description: 'Notification that 2FA has been enabled.',
    trigger: '2FA Enabled',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: '2FA has been Enabled',
    body: '<p>Hi {{firstName}}, Two-Factor Authentication is now active on your account.</p>',
    plainTextBody: 'Hi {{firstName}}, 2FA is now active on your account.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'TWO_FACTOR_DISABLED',
    channel: 'EMAIL',
    category: 'SECURITY',
    description: 'Notification that 2FA has been disabled.',
    trigger: '2FA Disabled',
    recipient: 'User',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Security Warning: 2FA has been Disabled',
    body: '<p>Hi {{firstName}}, Two-Factor Authentication has been disabled for your account. We recommend keeping it active for better security.</p>',
    plainTextBody: 'Hi {{firstName}}, 2FA has been disabled for your account.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- CUSTOMER ---
  {
    templateCode: 'JOB_POSTED_SUCCESS',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Confirmation that a job has been posted.',
    trigger: 'Job Posted',
    recipient: 'Customer',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Your Job Request is Live: {{service}}',
    body: '<p>Hi {{firstName}}, your request for <b>{{service}}</b> has been successfully posted.</p>',
    plainTextBody: 'Hi {{firstName}}, your job request for {{service}} is now live.',
    placeholders: ['firstName', 'service'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'JOB_REQUEST_CONFIRMATION',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Detailed confirmation after job creation.',
    trigger: 'Job Request Created',
    recipient: 'Customer',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Job Request Confirmed - {{serviceName}}',
    body: '<p>Hi {{firstName}},</p><p>We have received your request for <b>{{serviceName}}</b>.</p><p>We are currently looking for the best professional for you. We will notify you once a provider accepts your request.</p><p>Job ID: {{jobId}}</p>',
    plainTextBody: 'Hi {{firstName}}, job request for {{serviceName}} confirmed. Job ID: {{jobId}}',
    placeholders: ['firstName', 'serviceName', 'jobId'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'PROVIDER_ASSIGNED',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Notification that a provider has accepted the job.',
    trigger: 'Provider Accepts Job',
    recipient: 'Customer',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Professional Assigned to Your Job!',
    body: '<p>Hi {{firstName}},</p><p>Good news! <b>{{providerName}}</b> has been assigned to your <b>{{serviceName}}</b> request.</p><p>You can now track their progress in the app.</p>',
    plainTextBody: 'Hi {{firstName}}, {{providerName}} has been assigned to your {{serviceName}} job.',
    placeholders: ['firstName', 'serviceName', 'providerName', 'jobId'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'PROVIDER_EN_ROUTE',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Alert when provider starts traveling to location.',
    trigger: 'Provider Starts Travel',
    recipient: 'Customer',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Pro Update: Provider is on the way!',
    body: '<p>Hi {{firstName}}, <b>{{providerName}}</b> is now en-route to your location for job <b>{{service}}</b>.</p>',
    plainTextBody: 'Hi {{firstName}}, {{providerName}} is on the way for job {{service}}.',
    placeholders: ['firstName', 'providerName', 'service'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'PROVIDER_ARRIVED',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Alert when provider reaches the location.',
    trigger: 'Provider Arrives',
    recipient: 'Customer',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Pro Alert: Provider has Arrived!',
    body: '<p>Hi {{firstName}},</p><p>Your professional for <b>{{serviceName}}</b> has arrived at the location.</p><p>Please meet them to start the work.</p>',
    plainTextBody: 'Hi {{firstName}}, your provider for {{serviceName}} has arrived.',
    placeholders: ['firstName', 'serviceName', 'jobId'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'WORK_STARTED',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Notification that work has officially begun.',
    trigger: 'Job Started',
    recipient: 'Customer',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Work has Started: {{service}}',
    body: '<p>Hi {{firstName}}, work on your job <b>{{service}}</b> has officially started.</p>',
    plainTextBody: 'Hi {{firstName}}, work on {{service}} has started.',
    placeholders: ['firstName', 'service'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'JOB_COMPLETED_RECEIPT',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Job completion notice with receipt attached.',
    trigger: 'Job Completed',
    recipient: 'Customer',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Your PieceJob Receipt - {{serviceName}}',
    body: '<p>Hi {{firstName}},</p><p>Your job <b>{{serviceName}}</b> has been completed successfully.</p><p>Please find your official receipt attached to this email.</p><p>Thank you for using PieceJob!</p>',
    plainTextBody: 'Hi {{firstName}}, your job {{serviceName}} is complete. Receipt attached.',
    placeholders: ['firstName', 'serviceName', 'jobId'],
    countryCode: 'GLOBAL',
    pdfSupport: true
  },
  {
    templateCode: 'JOB_CANCELLED',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Notice of job cancellation.',
    trigger: 'Job Cancelled',
    recipient: 'User',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Job Cancelled - {{serviceName}}',
    body: '<p>Hi {{firstName}},</p><p>The job <b>{{serviceName}}</b> has been cancelled by the {{cancelledBy}}.</p><p>Reason: {{reason}}</p>',
    plainTextBody: 'Hi {{firstName}}, job {{serviceName}} cancelled by {{cancelledBy}}. Reason: {{reason}}',
    placeholders: ['firstName', 'serviceName', 'cancelledBy', 'reason'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'NEGOTIATION_ACCEPTED',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Notice when price negotiation is successful.',
    trigger: 'Price Accepted',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Negotiation Success! Price Agreed',
    body: '<p>Hi {{firstName}},</p><p>A final price of <b>{{amount}}</b> has been agreed for job <b>{{serviceName}}</b>.</p><p>The provider is now authorized to proceed.</p>',
    plainTextBody: 'Hi {{firstName}}, price of {{amount}} agreed for {{serviceName}}.',
    placeholders: ['firstName', 'amount', 'jobId', 'serviceName'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'NEGOTIATION_TERMINATED',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Notice when negotiation fails and job is reset.',
    trigger: 'Negotiation Rejected/Failed',
    recipient: 'Customer',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Negotiation Terminated',
    body: '<p>Hi {{firstName}},</p><p>The negotiation for job <b>{{serviceName}}</b> has been terminated. The job has been re-broadcasted to other professionals.</p>',
    plainTextBody: 'Hi {{firstName}}, negotiation for {{serviceName}} terminated.',
    placeholders: ['firstName', 'jobId', 'serviceName'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'NEGOTIATION_EXPIRED',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Notice when negotiation expires due to inactivity.',
    trigger: 'Negotiation Timeout',
    recipient: 'Customer',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Negotiation Expired - PieceJob',
    body: '<p>Hi {{firstName}},</p><p>The price negotiation for job <b>{{serviceName}}</b> has expired due to inactivity.</p><p>Please restart the negotiation or re-post the job if you still need the service.</p>',
    plainTextBody: 'Hi {{firstName}}, negotiation for {{serviceName}} expired.',
    placeholders: ['firstName', 'serviceName', 'jobId'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'RATING_REMINDER',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Follow-up to rate the provider after job completion.',
    trigger: 'Post-Job Follow-up',
    recipient: 'Customer',
    priority: 'LOW',
    language: 'EN',
    subject: 'How was your experience with {{providerName}}?',
    body: '<p>Hi {{firstName}}, please take a moment to rate your professional <b>{{providerName}}</b> for the recently completed <b>{{service}}</b>.</p>',
    plainTextBody: 'Hi {{firstName}}, please rate {{providerName}} for job {{service}}.',
    placeholders: ['firstName', 'providerName', 'service'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'REFUND_PROCESSED',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Confirmation that a refund has been initiated.',
    trigger: 'Refund Action',
    recipient: 'Customer',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Refund Confirmed: {{currency}} {{amount}}',
    body: '<p>Hi {{firstName}}, a refund of <b>{{currency}} {{amount}}</b> for job <b>#{{jobId}}</b> has been processed to your credit balance.</p>',
    plainTextBody: 'Hi {{firstName}}, refund of {{currency}} {{amount}} processed for job {{jobId}}.',
    placeholders: ['firstName', 'amount', 'currency', 'jobId'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- PROVIDER ---
  {
    templateCode: 'NEW_JOB_MATCH_ALERT',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Notification to provider that a nearby job matches their skills.',
    trigger: 'Job Match',
    recipient: 'Provider',
    priority: 'HIGH',
    language: 'EN',
    subject: 'New Job Opportunity: {{service}} near you!',
    body: '<p>Hi {{firstName}}, a new request for <b>{{service}}</b> in <b>{{location}}</b> matches your profile. Open the app to view details and accept.</p>',
    plainTextBody: 'Hi {{firstName}}, new job: {{service}} in {{location}}.',
    placeholders: ['firstName', 'service', 'location'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'PROVIDER_NET_EARNINGS',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Receipt of earnings released to provider wallet.',
    trigger: 'Escrow Release',
    recipient: 'Provider',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Earnings Credited! Job #{{jobId}}',
    body: '<p>Hi {{firstName}},</p><p>Good news! Your net earnings of <b>{{currency}} {{amount}}</b> for job <b>{{serviceName}}</b> have been released to your main balance.</p>',
    plainTextBody: 'Hi {{firstName}}, earnings of {{currency}} {{amount}} released for job {{jobId}}.',
    placeholders: ['firstName', 'amount', 'currency', 'jobId', 'serviceName'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'PROVIDER_VERIFICATION_APPROVED',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Welcome notice when provider verification is successful.',
    trigger: 'Verification Approved',
    recipient: 'Provider',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Verification Approved - Welcome Pro!',
    body: '<p>Hi {{firstName}},</p><p>Congratulations! Your professional verification has been approved. You can now start accepting jobs in the PieceJob network.</p><p>Go online now to start earning!</p>',
    plainTextBody: 'Hi {{firstName}}, your verification is approved! Welcome to PieceJob.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'PROVIDER_VERIFICATION_REJECTED',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Notice when provider verification fails.',
    trigger: 'Verification Rejected',
    recipient: 'Provider',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Verification Update - PieceJob',
    body: '<p>Hi {{firstName}},</p><p>We have reviewed your verification documents. Unfortunately, we could not approve your profile at this time.</p><p>Reason: {{reason}}</p><p>Please update your details and try again.</p>',
    plainTextBody: 'Hi {{firstName}}, verification rejected. Reason: {{reason}}',
    placeholders: ['firstName', 'reason'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'SERVICE_FEE_RECEIPT',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Confirmation of service fee payment (debt settlement).',
    trigger: 'Voucher Redemption / Credit Apply',
    recipient: 'Provider',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Service Fee Payment Received',
    body: '<p>Hi {{firstName}},</p><p>Thank you for your payment of <b>{{currency}} {{amount}}</b> toward your service fees.</p><p>Payment Method: {{vendor}}</p>',
    plainTextBody: 'Hi {{firstName}}, service fee payment of {{currency}} {{amount}} received via {{vendor}}.',
    placeholders: ['firstName', 'amount', 'currency', 'vendor'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'SERVICE_FEE_REMINDER',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Reminder to pay outstanding service fee debt.',
    trigger: '24h Balance Check',
    recipient: 'Provider',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Action Required: Service Fee Balance Reminder',
    body: '<p>Hi {{firstName}},</p><p>This is a reminder that you have an outstanding service fee balance of <b>{{currency}} {{balance}}</b>.</p><p>Please note that accounts with a balance exceeding <b>{{currency}} {{threshold}}</b> will be automatically suspended until settled.</p><p>You can pay your fees in the app using our voucher system.</p>',
    plainTextBody: 'Hi {{firstName}}, outstanding service fee balance: {{currency}} {{balance}}.',
    placeholders: ['firstName', 'balance', 'currency', 'threshold'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'PROVIDER_UNABLE_TO_LOCATE',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Notice to customer that provider is struggling to find them.',
    trigger: 'Unable to Locate Button',
    recipient: 'Customer',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Alert: Provider Unable to Locate You',
    body: '<p>Hi {{firstName}},</p><p>Your professional for <b>{{serviceName}}</b> is at the location but is unable to find you.</p><p>Please contact them via chat or phone immediately to avoid job cancellation.</p>',
    plainTextBody: 'Hi {{firstName}}, your provider for {{serviceName}} is at the location but can\'t find you.',
    placeholders: ['firstName', 'serviceName', 'jobId'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'UNSUSPENDED_NOTICE',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Notice that account suspension has been lifted.',
    trigger: 'Manual/Auto Unsuspend',
    recipient: 'Provider',
    priority: 'HIGH',
    language: 'EN',
    subject: 'PieceJob Account Unlocked: Ready to Work!',
    body: '<p>Hi {{firstName}}, your account suspension has been lifted. You can now go online and receive job matches.</p>',
    plainTextBody: 'Hi {{firstName}}, your account is no longer suspended.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- WALLET ---
  {
    templateCode: 'WALLET_CREDITED',
    channel: 'EMAIL',
    category: 'WALLET',
    description: 'Alert for any incoming wallet credit.',
    trigger: 'Wallet Mutation (Credit)',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Wallet Update: Funds Credited',
    body: '<p>Hi {{firstName}},</p><p>Your PieceJob wallet has been credited with <b>{{currency}} {{amount}}</b>.</p><p>Description: {{description}}</p><p>New Balance: {{balance}}</p>',
    plainTextBody: 'Hi {{firstName}}, wallet credited with {{currency}} {{amount}}. New balance: {{balance}}.',
    placeholders: ['firstName', 'amount', 'currency', 'description', 'balance'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'WALLET_DEBITED',
    channel: 'EMAIL',
    category: 'WALLET',
    description: 'Alert for any outgoing wallet payment.',
    trigger: 'Wallet Mutation (Debit)',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Wallet Update: Payment Processed',
    body: '<p>Hi {{firstName}},</p><p>A payment of <b>{{currency}} {{amount}}</b> was processed from your wallet.</p><p>Description: {{description}}</p><p>Remaining Balance: {{balance}}</p>',
    plainTextBody: 'Hi {{firstName}}, wallet debited for {{currency}} {{amount}}. Remaining balance: {{balance}}.',
    placeholders: ['firstName', 'amount', 'currency', 'description', 'balance'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'WITHDRAWAL_REQUESTED',
    channel: 'EMAIL',
    category: 'WALLET',
    description: 'Confirmation that withdrawal request is logged.',
    trigger: 'Withdrawal Action',
    recipient: 'Provider',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Withdrawal Request Received',
    body: '<p>Hi {{firstName}},</p><p>We have received your withdrawal request for <b>{{currency}} {{amount}}</b>. Our finance team will process it within the next business window.</p>',
    plainTextBody: 'Hi {{firstName}}, withdrawal request for {{currency}} {{amount}} received.',
    placeholders: ['firstName', 'amount', 'currency'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'WITHDRAWAL_COMPLETED',
    channel: 'EMAIL',
    category: 'WALLET',
    description: 'Confirmation that withdrawal has been paid to bank.',
    trigger: 'Payout Mark Paid',
    recipient: 'Provider',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Withdrawal Completed Successfully',
    body: '<p>Hi {{firstName}},</p><p>Your withdrawal of <b>{{currency}} {{amount}}</b> has been processed successfully.</p><p>Bank Reference: {{reference}}</p>',
    plainTextBody: 'Hi {{firstName}}, withdrawal of {{currency}} {{amount}} processed. Ref: {{reference}}.',
    placeholders: ['firstName', 'amount', 'currency', 'reference'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'WITHDRAWAL_FAILED',
    channel: 'EMAIL',
    category: 'WALLET',
    description: 'Notice of failed withdrawal and funds reversal.',
    trigger: 'Payout Reverse',
    recipient: 'Provider',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Withdrawal Request Failed',
    body: '<p>Hi {{firstName}},</p><p>We were unable to process your withdrawal of <b>{{currency}} {{amount}}</b>.</p><p>Reason: {{reason}}</p><p>The funds have been returned to your wallet.</p>',
    plainTextBody: 'Hi {{firstName}}, withdrawal of {{currency}} {{amount}} failed. Reason: {{reason}}.',
    placeholders: ['firstName', 'amount', 'currency', 'reason'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'TOP_UP_SUCCESS',
    channel: 'EMAIL',
    category: 'WALLET',
    description: 'Success notice after adding funds to main wallet.',
    trigger: 'Payment Gateway Callback',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Top-up Successful! {{currency}} {{amount}} Added',
    body: '<p>Hi {{firstName}}, your top-up of <b>{{currency}} {{amount}}</b> was successful. Your new balance is <b>{{balance}}</b>.</p>',
    plainTextBody: 'Hi {{firstName}}, top-up of {{currency}} {{amount}} successful.',
    placeholders: ['firstName', 'amount', 'currency', 'balance'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'VOUCHER_REDEEMED',
    channel: 'EMAIL',
    category: 'WALLET',
    description: 'Confirmation of voucher redemption.',
    trigger: 'Voucher Apply',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Voucher Redeemed: {{currency}} {{amount}}',
    body: '<p>Hi {{firstName}}, your voucher worth <b>{{currency}} {{amount}}</b> has been redeemed successfully.</p>',
    plainTextBody: 'Hi {{firstName}}, voucher for {{currency}} {{amount}} redeemed.',
    placeholders: ['firstName', 'amount', 'currency'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- REFERRAL ---
  {
    templateCode: 'REFERRAL_REWARD_EARNED',
    channel: 'EMAIL',
    category: 'REFERRAL',
    description: 'Notification to referrer that their reward is credited.',
    trigger: 'Referral Qualified Job Complete',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'You Earned a Referral Reward!',
    body: '<p>Hi {{firstName}},</p><p>Congratulations! You have earned a reward of <b>{{currency}} {{amount}}</b> because {{referredName}} completed their qualifying job.</p><p>Your reward has been credited to your wallet.</p>',
    plainTextBody: 'Hi {{firstName}}, you earned a reward of {{currency}} {{amount}} from {{referredName}}\'s referral.',
    placeholders: ['firstName', 'referredName', 'amount', 'currency'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'REFERRAL_REGISTRATION_SUCCESS',
    channel: 'EMAIL',
    category: 'REFERRAL',
    description: 'Notification that someone joined using the referrer\'s code.',
    trigger: 'Referral Registered',
    recipient: 'User',
    priority: 'LOW',
    language: 'EN',
    subject: 'Good News: Someone just joined with your code!',
    body: '<p>Hi {{firstName}}, a new user joined PieceJob using your referral code. You\'ll earn a reward once they complete their first job.</p>',
    plainTextBody: 'Hi {{firstName}}, someone joined with your code!',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- AFFILIATE ---
  {
    templateCode: 'WELCOME_PARTNER',
    channel: 'EMAIL',
    category: 'AFFILIATE',
    description: 'Onboarding notice for new affiliate partners.',
    trigger: 'Partner Account Created',
    recipient: 'Partner',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Welcome to the PieceJob Affiliate Program!',
    body: '<h1>Partner Onboarding Successful</h1><p>Hi {{name}},</p><p>Welcome to our affiliate network. Your unique referral code is: <b>{{referralCode}}</b></p><p>You can login to the Partner Portal using your email and temporary password: <b>{{password}}</b></p>',
    plainTextBody: 'Hi {{name}}, welcome to PieceJob Affiliate Program. Code: {{referralCode}}.',
    placeholders: ['name', 'referralCode', 'password'],
    countryCode: 'GLOBAL'
  },

  // --- ADMIN ---
  {
    templateCode: 'ADMIN_DAILY_SUMMARY',
    channel: 'EMAIL',
    category: 'ADMIN',
    description: '24-hour performance scorecard for Super Admins.',
    trigger: 'Scheduler (Daily)',
    recipient: 'Admin',
    priority: 'LOW',
    language: 'EN',
    subject: 'PieceJob Daily Platform Summary - {{date}}',
    body: '<h2>Platform Performance Summary</h2><p>Date: {{date}}</p><ul><li>New Users: {{newUsers}}</li><li>New Jobs: {{newJobs}}</li><li>Completed Jobs: {{completedJobs}}</li><li>Total Revenue: {{totalRevenue}}</li></ul><p>Workspace: {{countryCode}}</p>',
    plainTextBody: 'Daily Summary for {{date}}: Users: {{newUsers}}, Jobs: {{newJobs}}, Revenue: {{totalRevenue}}.',
    placeholders: ['date', 'newUsers', 'newJobs', 'completedJobs', 'totalRevenue', 'countryCode'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'ADMIN_WEEKLY_SUMMARY',
    channel: 'EMAIL',
    category: 'ADMIN',
    description: '7-day performance report per workspace.',
    trigger: 'Scheduler (Weekly)',
    recipient: 'Admin',
    priority: 'LOW',
    language: 'EN',
    subject: 'PieceJob Weekly Workspace Performance Report - {{countryCode}}',
    body: '<h2>Weekly Performance Scorecard</h2><p>Period: {{period}}</p><ul><li>Total New Users: {{totalUsers}}</li><li>Total Jobs Created: {{totalJobs}}</li><li>Total Revenue Generated: {{totalRevenue}}</li></ul><p>Workspace: {{countryCode}}</p>',
    plainTextBody: 'Weekly Summary for {{countryCode}}: Period {{period}}, Users: {{totalUsers}}, Revenue: {{totalRevenue}}.',
    placeholders: ['period', 'totalUsers', 'totalJobs', 'totalRevenue', 'countryCode'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'TEST_EMAIL',
    channel: 'EMAIL',
    category: 'ADMIN',
    description: 'Diagnostic signal to verify SMTP node connectivity.',
    trigger: 'Admin Action',
    recipient: 'Admin',
    priority: 'HIGH',
    language: 'EN',
    subject: 'SMTP Oracle Connectivity Test Signal',
    body: '<h1>Oracle Signal Established</h1><p>Time: {{time}}</p><p>Recipient: {{recipient}}</p><p>This test signal confirms that your SMTP dispatch node is operational.</p>',
    plainTextBody: 'Oracle Signal Established at {{time}}. Node operational.',
    placeholders: ['time', 'recipient'],
    countryCode: 'GLOBAL'
  },

  // --- MARKETING ---
  {
    templateCode: 'MARKETING_ANNOUNCEMENT',
    channel: 'EMAIL',
    category: 'MARKETING',
    description: 'Generic announcement template for custom broadcasts.',
    trigger: 'Admin Campaign Dispatch',
    recipient: 'Target Segment',
    priority: 'LOW',
    language: 'EN',
    subject: '{{subject}}',
    body: '<p>Hi {{firstName}},</p><div>{{body}}</div>',
    plainTextBody: 'Hi {{firstName}}, {{body}}',
    placeholders: ['firstName', 'subject', 'body'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'WORKSPACE_LAUNCH_ALERT',
    channel: 'EMAIL',
    category: 'MARKETING',
    description: 'Alert for launching PieceJob in a new region.',
    trigger: 'Marketing Campaign',
    recipient: 'Interested Users',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'PieceJob has Arrived in {{location}}!',
    body: '<h1>We are Live!</h1><p>Hi {{firstName}}, we are excited to announce that PieceJob is now fully operational in <b>{{location}}</b>.</p>',
    plainTextBody: 'PieceJob is now live in {{location}}!',
    placeholders: ['firstName', 'location'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- LEGAL ---
  {
    templateCode: 'PRIVACY_POLICY_UPDATE',
    channel: 'EMAIL',
    category: 'LEGAL',
    description: 'Mandatory notice when privacy terms change.',
    trigger: 'Policy Update',
    recipient: 'All Users',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Important: Updates to our Privacy Policy',
    body: '<p>Hi {{firstName}}, we have updated our Privacy Policy to better serve you. Please review the changes here: <a href="{{link}}">Privacy Policy</a>.</p>',
    plainTextBody: 'Hi {{firstName}}, we updated our Privacy Policy. View here: {{link}}',
    placeholders: ['firstName', 'link'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'TERMS_AND_CONDITIONS_UPDATE',
    channel: 'EMAIL',
    category: 'LEGAL',
    description: 'Mandatory notice when user agreement changes.',
    trigger: 'T&C Update',
    recipient: 'All Users',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Update to PieceJob Terms and Conditions',
    body: '<p>Hi {{firstName}}, we have updated our Terms and Conditions. Your continued use of the app constitutes agreement to these terms.</p>',
    plainTextBody: 'Hi {{firstName}}, we updated our Terms and Conditions.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'GDPR_DATA_EXPORT_READY',
    channel: 'EMAIL',
    category: 'LEGAL',
    description: 'Notification that user data export is ready for download.',
    trigger: 'Admin Export Action',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Your Personal Data Export is Ready',
    body: '<p>Hi {{firstName}}, your data export requested on {{date}} is now ready for download. <a href="{{downloadUrl}}">Download Link</a></p>',
    plainTextBody: 'Hi {{firstName}}, your data export is ready: {{downloadUrl}}',
    placeholders: ['firstName', 'date', 'downloadUrl'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- FINANCIALS ---
  {
    templateCode: 'TAX_INVOICE',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Official tax invoice for job payments.',
    trigger: 'Invoice Generation',
    recipient: 'Customer',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Tax Invoice - {{invoiceNumber}}',
    body: '<p>Hi {{firstName}},</p><p>Please find your tax invoice for invoice number <b>{{invoiceNumber}}</b> attached to this email.</p><p>Amount: <b>{{amount}}</b></p>',
    plainTextBody: 'Hi {{firstName}}, tax invoice {{invoiceNumber}} for {{amount}} attached.',
    placeholders: ['firstName', 'invoiceNumber', 'amount', 'invoiceId'],
    countryCode: 'GLOBAL',
    pdfSupport: true
  },
  {
    templateCode: 'MONTHLY_STATEMENT',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Monthly summary of provider activities and earnings.',
    trigger: 'Monthly Scheduler',
    recipient: 'Provider',
    priority: 'LOW',
    language: 'EN',
    subject: 'Your Monthly PieceJob Statement - {{period}}',
    body: '<p>Hi {{firstName}},</p><p>Your monthly statement for the period <b>{{period}}</b> is ready.</p><p>Please find the detailed report attached as a PDF.</p>',
    plainTextBody: 'Hi {{firstName}}, your monthly statement for {{period}} is ready.',
    placeholders: ['firstName', 'period', 'statementId'],
    countryCode: 'GLOBAL',
    pdfSupport: true
  },
  {
    templateCode: 'FAILED_PAYMENT',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Alert when a payment transaction fails.',
    trigger: 'Gateway Error',
    recipient: 'Customer',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Payment Failed - PieceJob',
    body: '<p>Hi {{firstName}},</p><p>We were unable to process your payment of <b>{{currency}} {{amount}}</b> for job ID <b>{{jobId}}</b>.</p><p>Reason: <b>{{reason}}</b></p><p>Please try again with a different payment method.</p>',
    plainTextBody: 'Hi {{firstName}}, payment of {{currency}} {{amount}} failed for job {{jobId}}.',
    placeholders: ['firstName', 'amount', 'currency', 'jobId', 'reason'],
    countryCode: 'GLOBAL'
  },
  {
    templateCode: 'BOOKING_EXPIRED',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Notice when a job booking expires without being accepted.',
    trigger: 'Broadcast Timeout',
    recipient: 'Customer',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Your Booking has Expired',
    body: '<p>Hi {{firstName}}, your booking for <b>{{service}}</b> has expired as no professional was able to accept it in time. We have refunded your booking fee.</p>',
    plainTextBody: 'Hi {{firstName}}, your booking for {{service}} has expired.',
    placeholders: ['firstName', 'service'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'TAX_INVOICE_VOIDED',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Notice when an invoice is voided by an admin.',
    trigger: 'Invoice Void',
    recipient: 'Customer',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Important: Invoice #{{invoiceNumber}} has been Voided',
    body: '<p>Hi {{firstName}}, the tax invoice <b>{{invoiceNumber}}</b> for your recent job has been voided. A replacement will be issued if applicable.</p>',
    plainTextBody: 'Hi {{firstName}}, invoice {{invoiceNumber}} was voided.',
    placeholders: ['firstName', 'invoiceNumber'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- PROVIDER ---
  {
    templateCode: 'EARNINGS_SUMMARY_WEEKLY',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Weekly summary of provider earnings and hours worked.',
    trigger: 'Weekly Scheduler',
    recipient: 'Provider',
    priority: 'LOW',
    language: 'EN',
    subject: 'Your PieceJob Weekly Earnings Summary',
    body: '<h1>Great Work!</h1><p>Hi {{firstName}}, here is a summary of your earnings for the week: <b>{{currency}} {{amount}}</b> over {{jobs}} completed jobs.</p>',
    plainTextBody: 'Hi {{firstName}}, you earned {{currency}} {{amount}} this week.',
    placeholders: ['firstName', 'currency', 'amount', 'jobs'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'BONUS_EARNED_ALERT',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Notice when a provider earns a performance or loyalty bonus.',
    trigger: 'Bonus Event',
    recipient: 'Provider',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'You have Earned a Bonus! {{currency}} {{amount}}',
    body: '<p>Congratulations {{firstName}}! You have been rewarded a bonus for your exceptional service on our platform.</p>',
    plainTextBody: 'Hi {{firstName}}, you earned a bonus of {{currency}} {{amount}}!',
    placeholders: ['firstName', 'currency', 'amount'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- WALLET ---
  {
    templateCode: 'WITHDRAWAL_BATCH_PROCESSING',
    channel: 'EMAIL',
    category: 'WALLET',
    description: 'Notice that a withdrawal has entered the batch processing stage.',
    trigger: 'Finance Action',
    recipient: 'Provider',
    priority: 'LOW',
    language: 'EN',
    subject: 'Update: Your Withdrawal is being Processed',
    body: '<p>Hi {{firstName}}, your withdrawal request for <b>{{currency}} {{amount}}</b> has been included in our latest payment batch.</p>',
    plainTextBody: 'Hi {{firstName}}, your withdrawal for {{currency}} {{amount}} is being processed.',
    placeholders: ['firstName', 'currency', 'amount'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'WALLET_LOW_BALANCE_REMINDER',
    channel: 'EMAIL',
    category: 'WALLET',
    description: 'Reminder for corporate or high-volume users to top up.',
    trigger: 'Balance Threshold',
    recipient: 'User',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Action Required: Your Wallet Balance is Low',
    body: '<p>Hi {{firstName}}, your wallet balance has dropped below <b>{{currency}} {{threshold}}</b>. Please top up to avoid service interruption.</p>',
    plainTextBody: 'Hi {{firstName}}, your wallet balance is low: {{currency}} {{balance}}.',
    placeholders: ['firstName', 'currency', 'threshold', 'balance'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- REFERRAL ---
  {
    templateCode: 'REFERRAL_MILESTONE_REACHED',
    channel: 'EMAIL',
    category: 'REFERRAL',
    description: 'Alert when a user hits a referral tier milestone.',
    trigger: 'Referral Count Achievement',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Referral Rockstar! Milestone Reached',
    body: '<p>Hi {{firstName}}, you have successfully referred <b>{{count}}</b> active users! You have unlocked a special reward.</p>',
    plainTextBody: 'Hi {{firstName}}, you referred {{count}} users! Milestone reached.',
    placeholders: ['firstName', 'count'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- AFFILIATE ---
  {
    templateCode: 'AFFILIATE_COMMISSION_PAID',
    channel: 'EMAIL',
    category: 'AFFILIATE',
    description: 'Notice to affiliate partner that commission has been paid.',
    trigger: 'Payout Paid (Partner)',
    recipient: 'Partner',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Commission Paid: {{currency}} {{amount}}',
    body: '<h1>Payment Dispatched</h1><p>Hi {{name}}, your monthly commission has been paid to your registered bank account. Reference: {{reference}}</p>',
    plainTextBody: 'Hi {{name}}, commission of {{currency}} {{amount}} paid. Ref: {{reference}}.',
    placeholders: ['name', 'currency', 'amount', 'reference'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- MARKETING ---
  {
    templateCode: 'NEWSLETTER_MONTHLY',
    channel: 'EMAIL',
    category: 'MARKETING',
    description: 'Standard monthly platform update newsletter.',
    trigger: 'Marketing Campaign',
    recipient: 'Subscribed Users',
    priority: 'LOW',
    language: 'EN',
    subject: 'The PieceJob Pulse: What\'s New this Month',
    body: '<h1>What\'s New?</h1><p>Hi {{firstName}}, here are the latest updates, stories, and tips from the PieceJob community.</p>',
    plainTextBody: 'Hi {{firstName}}, check out the latest from PieceJob!',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'ABANDONED_BOOKING_REMINDER',
    channel: 'EMAIL',
    category: 'MARKETING',
    description: 'Nudge for customers who left a booking in draft/pre-payment.',
    trigger: 'Cart Abandonment (24h)',
    recipient: 'Customer',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Still need a {{service}}?',
    body: '<p>Hi {{firstName}}, we noticed you started a request for <b>{{service}}</b> but didn\'t finish. Need any help completing your booking?</p>',
    plainTextBody: 'Hi {{firstName}}, do you still need a {{service}}?',
    placeholders: ['firstName', 'service'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- LEGAL ---
  {
    templateCode: 'ACCOUNT_BANNED_NOTICE',
    channel: 'EMAIL',
    category: 'LEGAL',
    description: 'Mandatory notice when a user is permanently banned.',
    trigger: 'Admin Action (Ban)',
    recipient: 'User',
    priority: 'URGENT',
    language: 'EN',
    subject: 'Notice: Permanent Account Ban',
    body: '<p>Hi {{firstName}}, your account has been permanently suspended for violations of our terms of service.</p><p>Reason: <b>{{reason}}</b></p>',
    plainTextBody: 'Hi {{firstName}}, your account is banned. Reason: {{reason}}',
    placeholders: ['firstName', 'reason'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- ADMIN ---
  {
    templateCode: 'SYSTEM_ERROR_ALERT',
    channel: 'EMAIL',
    category: 'ADMIN',
    description: 'Critical alert for system-level failures.',
    trigger: 'Error Handler',
    recipient: 'Dev Team / Super Admin',
    priority: 'URGENT',
    language: 'EN',
    subject: 'CRITICAL: System Error Detected [{{env}}]',
    body: '<h2>System Error Log</h2><p>Error: {{errorMessage}}</p><p>Module: {{module}}</p><p>Timestamp: {{time}}</p>',
    plainTextBody: 'CRITICAL ERROR: {{errorMessage}} in {{module}} at {{time}}.',
    placeholders: ['env', 'errorMessage', 'module', 'time'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'FRAUD_ALERT_HIGH_RISK',
    channel: 'EMAIL',
    category: 'ADMIN',
    description: 'Alert for high-risk fraud scores or circular referrals.',
    trigger: 'Fraud Engine',
    recipient: 'Fraud Team / Super Admin',
    priority: 'HIGH',
    language: 'EN',
    subject: 'FRAUD ALERT: High Risk Activity [{{userId}}]',
    body: '<h2>Fraud Score: {{score}}</h2><p>User: {{userId}}</p><p>Activity: {{activity}}</p>',
    plainTextBody: 'FRAUD ALERT: User {{userId}} activity detected.',
    placeholders: ['userId', 'score', 'activity'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'VERIFICATION_QUEUE_THRESHOLD',
    channel: 'EMAIL',
    category: 'ADMIN',
    description: 'Alert when pending verification queue exceeds defined threshold.',
    trigger: 'Cron Monitor',
    recipient: 'Operations Admin',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Operational Alert: Verification Queue backlog [{{count}}]',
    body: '<p>The pending provider verification queue currently has <b>{{count}}</b> pending requests. Please assign staff to clear the backlog.</p>',
    plainTextBody: 'Verification Queue has {{count}} pending requests.',
    placeholders: ['count'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'LOW_VOUCHER_STOCK_ALERT',
    channel: 'EMAIL',
    category: 'ADMIN',
    description: 'Alert when manual voucher inventory is low.',
    trigger: 'Voucher Generation',
    recipient: 'Inventory Admin',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Inventory Alert: Low Voucher Stock [{{vendor}}]',
    body: '<p>Only <b>{{remaining}}</b> vouchers left for <b>{{vendor}}</b>. Please generate more to avoid disruption.</p>',
    plainTextBody: 'Low stock for {{vendor}}: {{remaining}} left.',
    placeholders: ['vendor', 'remaining'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },

  // --- FUTURE READY / OTHERS ---
  {
    templateCode: 'WORKSPACE_REVENUE_REPORT_WEEKLY',
    channel: 'EMAIL',
    category: 'ADMIN',
    description: 'Weekly financial performance summary per workspace.',
    trigger: 'Scheduler',
    recipient: 'Country Admin',
    priority: 'LOW',
    language: 'EN',
    subject: 'Financial Scorecard: {{country}} Weekly Report',
    body: '<h2>{{country}} Weekly Revenue</h2><p>Total Revenue: {{currency}} {{revenue}}</p><p>Total Payouts: {{currency}} {{payouts}}</p>',
    plainTextBody: '{{country}} Revenue: {{currency}} {{revenue}}.',
    placeholders: ['country', 'currency', 'revenue', 'payouts'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'SERVICE_QUALITY_WARNING',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Notice to provider when their rating drops near suspension threshold.',
    trigger: 'Rating Logic',
    recipient: 'Provider',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Urgent: Your service rating has dropped',
    body: '<p>Hi {{firstName}}, your current rating is <b>{{rating}}</b>. If it falls below {{threshold}}, your account may be restricted.</p>',
    plainTextBody: 'Hi {{firstName}}, your rating is {{rating}}. Minimum: {{threshold}}.',
    placeholders: ['firstName', 'rating', 'threshold'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'AFFILIATE_REPORT_MONTHLY',
    channel: 'EMAIL',
    category: 'AFFILIATE',
    description: 'Monthly performance report for affiliate partners.',
    trigger: 'Monthly Scheduler',
    recipient: 'Partner',
    priority: 'LOW',
    language: 'EN',
    subject: 'Your PieceJob Affiliate Monthly Impact Report',
    body: '<h1>Monthly Impact</h1><p>Hi {{name}}, your referral code drove <b>{{registrations}}</b> new users and <b>{{jobs}}</b> jobs this month.</p>',
    plainTextBody: 'Hi {{name}}, you drove {{registrations}} registrations this month.',
    placeholders: ['name', 'registrations', 'jobs'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'REFERRAL_REWARD_PENDING',
    channel: 'EMAIL',
    category: 'REFERRAL',
    description: 'Notification that a reward is earned but in the cooling/validation period.',
    trigger: 'Referral Qualified',
    recipient: 'User',
    priority: 'LOW',
    language: 'EN',
    subject: 'Reward Pending! {{currency}} {{amount}} is on the way',
    body: '<p>Hi {{firstName}}, great news! {{referredName}} just completed their first job. Your reward is currently being validated and will be released in {{days}} days.</p>',
    plainTextBody: 'Hi {{firstName}}, reward of {{currency}} {{amount}} is pending.',
    placeholders: ['firstName', 'referredName', 'amount', 'currency', 'days'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'JOB_RESCHEDULED_NOTICE',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Notice when a job\'s scheduled time is changed.',
    trigger: 'Job Update',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Update: Your Job has been Rescheduled',
    body: '<p>Hi {{firstName}}, the job <b>{{service}}</b> has been moved to <b>{{newTime}}</b>.</p>',
    plainTextBody: 'Hi {{firstName}}, job {{service}} rescheduled to {{newTime}}.',
    placeholders: ['firstName', 'service', 'newTime'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'DATA_BREACH_NOTICE',
    channel: 'EMAIL',
    category: 'SECURITY',
    description: 'Mandatory security breach notification.',
    trigger: 'Emergency Admin Action',
    recipient: 'Affected Users',
    priority: 'URGENT',
    language: 'EN',
    subject: 'Important Security Update regarding your account',
    body: '<p>Hi {{firstName}}, we are writing to inform you of a potential security incident. We have taken steps to secure your data...</p>',
    plainTextBody: 'Important Security Update for {{firstName}}.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'IP_BLACKLIST_NOTIFICATION',
    channel: 'EMAIL',
    category: 'SECURITY',
    description: 'Alert to admin when an IP is blacklisted by the firewall.',
    trigger: 'Security Engine',
    recipient: 'Security Team',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Security: IP Address Blacklisted [{{ip}}]',
    body: '<p>The IP <b>{{ip}}</b> has been blacklisted after {{attempts}} suspicious attempts.</p>',
    plainTextBody: 'IP {{ip}} blacklisted after {{attempts}} attempts.',
    placeholders: ['ip', 'attempts'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'BADGE_EARNED_LEVEL_UP',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Congratulations email when a provider reaches a new tier.',
    trigger: 'Tier Promotion',
    recipient: 'Provider',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'You\'ve Leveled Up! Welcome to {{tier}} Tier',
    body: '<p>Amazing work {{firstName}}! You are now a <b>{{tier}}</b> professional. You now have access to higher value jobs and lower service fees.</p>',
    plainTextBody: 'Congratulations {{firstName}}, you are now a {{tier}} pro!',
    placeholders: ['firstName', 'tier'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'DISPUTE_RAISED_NOTICE',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Confirmation that a dispute has been opened.',
    trigger: 'Support Action',
    recipient: 'Customer',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Dispute Opened: Ticket #{{ticketId}}',
    body: '<p>Hi {{firstName}}, we have opened a formal dispute for job <b>#{{jobId}}</b>. Our support team will review the evidence and contact you shortly.</p>',
    plainTextBody: 'Dispute opened for job {{jobId}}. Ticket: {{ticketId}}.',
    placeholders: ['firstName', 'jobId', 'ticketId'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'DISPUTE_RESOLVED_NOTICE',
    channel: 'EMAIL',
    category: 'CUSTOMER',
    description: 'Outcome of a formal dispute.',
    trigger: 'Support Resolution',
    recipient: 'User',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Update: Dispute #{{ticketId}} Resolved',
    body: '<p>Hi {{firstName}}, the dispute regarding job <b>#{{jobId}}</b> has been resolved. Outcome: <b>{{resolution}}</b></p>',
    plainTextBody: 'Dispute {{ticketId}} resolved. Outcome: {{resolution}}.',
    placeholders: ['firstName', 'jobId', 'ticketId', 'resolution'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'PROVIDER_BAD_BEHAVIOR_WARNING',
    channel: 'EMAIL',
    category: 'PROVIDER',
    description: 'Formal warning for conduct violations.',
    trigger: 'Admin Action',
    recipient: 'Provider',
    priority: 'HIGH',
    language: 'EN',
    subject: 'Formal Warning: Conduct on PieceJob Platform',
    body: '<p>Hi {{firstName}}, this is a formal warning regarding reported behavior on the platform. Further violations may result in account termination.</p>',
    plainTextBody: 'Formal warning for {{firstName}}.',
    placeholders: ['firstName'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'NEW_SERVICE_CATEGORY_ALERT',
    channel: 'EMAIL',
    category: 'MARKETING',
    description: 'Alert when a major new service category is added.',
    trigger: 'Marketing Campaign',
    recipient: 'All Users',
    priority: 'LOW',
    language: 'EN',
    subject: 'Now Available: {{categoryName}} on PieceJob!',
    body: '<p>Hi {{firstName}}, we are excited to introduce <b>{{categoryName}}</b> services! From {{examples}}, you can now find even more professionals on PieceJob.</p>',
    plainTextBody: 'New category: {{categoryName}} now available!',
    placeholders: ['firstName', 'categoryName', 'examples'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'ACCOUNT_SUSPENDED_APPEAL_RECEIVED',
    channel: 'EMAIL',
    category: 'ACCOUNT',
    description: 'Confirmation that an appeal for a suspension was received.',
    trigger: 'Support Action',
    recipient: 'User',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'Appeal Received: Ticket #{{ticketId}}',
    body: '<p>Hi {{firstName}}, we have received your appeal regarding your account suspension. We will notify you of the outcome within 48 hours.</p>',
    plainTextBody: 'Appeal received for ticket {{ticketId}}.',
    placeholders: ['firstName', 'ticketId'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  },
  {
    templateCode: 'LOYALTY_REWARD_CLAIMABLE',
    channel: 'EMAIL',
    category: 'MARKETING',
    description: 'Offer for loyal users to claim a reward.',
    trigger: 'Promo Engine',
    recipient: 'Loyal Users',
    priority: 'MEDIUM',
    language: 'EN',
    subject: 'A Gift for You: Claim your {{reward}}',
    body: '<p>Hi {{firstName}}, as a thank you for being a top user, you can claim <b>{{reward}}</b> for your next booking!</p>',
    plainTextBody: 'Claim your {{reward}} today!',
    placeholders: ['firstName', 'reward'],
    countryCode: 'GLOBAL',
    isFutureReady: true
  }
];

const seed = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB');

    let createdCount = 0;
    let skippedCount = 0;

    for (const t of templates) {
      const existing = await NotificationTemplate.findOne({
          templateCode: t.templateCode,
          channel: t.channel,
          countryCode: t.countryCode
      });

      if (existing) {
          skippedCount++;
          continue;
      }

      await NotificationTemplate.create(t);
      createdCount++;
      console.log(`Seeded new template: ${t.templateCode}`);
    }

    console.log(`Seeding complete: ${createdCount} created, ${skippedCount} skipped.`);

    // Ensure Global Config has SECURITY category enabled
    await EmailConfig.findOneAndUpdate(
      { countryCode: 'GLOBAL' },
      {
        $set: {
          'enabledCategories.SECURITY': true
        }
      }
    );

    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }
};

seed();
